// Code generator for OLED GUI Editor
import type { Project, Page, PageLink, Element, ProjectConfig } from '@/types'

export function generateCode(project: Project): { name: string; content: string }[] {
  const files: { name: string; content: string }[] = []
  const config = project.config

  // Generate driver files
  files.push({
    name: 'oled_driver.h',
    content: generateDriverHeader(config)
  })

  files.push({
    name: 'oled_driver.c',
    content: generateDriverSource(config)
  })

  // Generate font file
  files.push({
    name: 'oled_font.h',
    content: generateFontHeader()
  })

  // Generate GUI framework files
  files.push({
    name: 'oled_gui.h',
    content: generateGUIHeader(project)
  })

  files.push({
    name: 'oled_gui.c',
    content: generateGUISource(project)
  })

  // Generate page files
  for (const page of project.pages) {
    const pageName = sanitizeName(page.name)
    files.push({
      name: `page_${pageName}.h`,
      content: generatePageHeader(page, config)
    })
    files.push({
      name: `page_${pageName}.c`,
      content: generatePageSource(page, config)
    })
  }

  // Generate image data if any
  const imageElements = project.pages.flatMap(p =>
    p.elements.filter(e => e.type === 'image')
  )
  if (imageElements.length > 0) {
    files.push({
      name: 'oled_images.h',
      content: generateImagesHeader(imageElements, config)
    })
  }

  return files
}

function sanitizeName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '_')
    .replace(/_+/g, '_')
    .replace(/^_|_$/g, '')
}

function generateDriverHeader(config: ProjectConfig): string {
  const date = new Date().toISOString().split('T')[0]
  const i2cAddr = (config.oled.i2cAddress << 1).toString(16).toUpperCase()

  return `/**
 * @file    oled_driver.h
 * @brief   OLED ${config.oled.driver} Driver
 * @author  ${config.author || 'OLED GUI Editor'}
 * @date    ${date}
 * @note    Generated by OLED GUI Editor
 */

#ifndef __OLED_DRIVER_H
#define __OLED_DRIVER_H

#ifdef __cplusplus
extern "C" {
#endif

${config.mcu.codeStyle === 'HAL' ? '#include "main.h"' : '#include <stdint.h>'}

/* OLED Configuration */
#define OLED_WIDTH          ${config.oled.width}
#define OLED_HEIGHT         ${config.oled.height}
#define OLED_PAGES          (OLED_HEIGHT / 8)

${config.oled.bus === 'I2C' ? `/* I2C Configuration */
#define OLED_I2C_ADDR       0x${i2cAddr}
` : `/* SPI Configuration */
#define OLED_USE_SPI        1
`}

/* Color Definitions */
#define OLED_COLOR_BLACK    0
#define OLED_COLOR_WHITE    1

/* Function Prototypes */
void OLED_Init(void);
void OLED_Clear(void);
void OLED_Fill(uint8_t color);
void OLED_Display(void);
void OLED_SetPixel(uint8_t x, uint8_t y, uint8_t color);
uint8_t OLED_GetPixel(uint8_t x, uint8_t y);

/* Drawing Functions */
void OLED_DrawLine(uint8_t x0, uint8_t y0, uint8_t x1, uint8_t y1, uint8_t color);
void OLED_DrawRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color);
void OLED_FillRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color);
void OLED_DrawCircle(uint8_t x, uint8_t y, uint8_t r, uint8_t color);
void OLED_FillCircle(uint8_t x, uint8_t y, uint8_t r, uint8_t color);
void OLED_DrawRoundRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t r, uint8_t color);
void OLED_FillRoundRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t r, uint8_t color);

/* Text Functions */
void OLED_SetCursor(uint8_t x, uint8_t y);
void OLED_DrawChar(uint8_t x, uint8_t y, char c, uint8_t size, uint8_t color);
void OLED_DrawString(uint8_t x, uint8_t y, const char* str, uint8_t size, uint8_t color);

/* Image Functions */
void OLED_DrawBitmap(uint8_t x, uint8_t y, uint8_t w, uint8_t h, const uint8_t* bitmap, uint8_t color);

#ifdef __cplusplus
}
#endif

#endif /* __OLED_DRIVER_H */
`
}

function generateDriverSource(config: ProjectConfig): string {
  const date = new Date().toISOString().split('T')[0]
  const isHAL = config.mcu.codeStyle === 'HAL'
  const isI2C = config.oled.bus === 'I2C'

  let i2cHandle = 'hi2c1'
  let spiHandle = 'hspi1'

  const initSequence = getInitSequence(config.oled.driver)

  return `/**
 * @file    oled_driver.c
 * @brief   OLED ${config.oled.driver} Driver Implementation
 * @author  ${config.author || 'OLED GUI Editor'}
 * @date    ${date}
 * @note    Generated by OLED GUI Editor
 */

#include "oled_driver.h"
#include "oled_font.h"
${isHAL ? `
extern I2C_HandleTypeDef ${i2cHandle};
` : ''}

/* Display Buffer */
static uint8_t OLED_Buffer[OLED_WIDTH * OLED_PAGES];

/* Private Functions */
static void OLED_WriteCmd(uint8_t cmd);
static void OLED_WriteData(uint8_t data);

/**
 * @brief Write command to OLED
 */
static void OLED_WriteCmd(uint8_t cmd)
{
${isHAL && isI2C ? `    uint8_t data[2] = {0x00, cmd};
    HAL_I2C_Master_Transmit(&${i2cHandle}, OLED_I2C_ADDR, data, 2, 100);` :
isHAL ? `    HAL_GPIO_WritePin(OLED_DC_GPIO_Port, OLED_DC_Pin, GPIO_PIN_RESET);
    HAL_GPIO_WritePin(OLED_CS_GPIO_Port, OLED_CS_Pin, GPIO_PIN_RESET);
    HAL_SPI_Transmit(&${spiHandle}, &cmd, 1, 100);
    HAL_GPIO_WritePin(OLED_CS_GPIO_Port, OLED_CS_Pin, GPIO_PIN_SET);` :
`    // TODO: Implement for your platform`}
}

/**
 * @brief Write data to OLED
 */
static void OLED_WriteData(uint8_t data)
{
${isHAL && isI2C ? `    uint8_t buf[2] = {0x40, data};
    HAL_I2C_Master_Transmit(&${i2cHandle}, OLED_I2C_ADDR, buf, 2, 100);` :
isHAL ? `    HAL_GPIO_WritePin(OLED_DC_GPIO_Port, OLED_DC_Pin, GPIO_PIN_SET);
    HAL_GPIO_WritePin(OLED_CS_GPIO_Port, OLED_CS_Pin, GPIO_PIN_RESET);
    HAL_SPI_Transmit(&${spiHandle}, &data, 1, 100);
    HAL_GPIO_WritePin(OLED_CS_GPIO_Port, OLED_CS_Pin, GPIO_PIN_SET);` :
`    // TODO: Implement for your platform`}
}

/**
 * @brief Initialize OLED display
 */
void OLED_Init(void)
{
${isHAL ? `    HAL_Delay(100);  // Wait for power stabilization
` : `    // Delay for power stabilization
`}
${initSequence}
    OLED_Clear();
    OLED_Display();
}

/**
 * @brief Clear display buffer
 */
void OLED_Clear(void)
{
    for (uint16_t i = 0; i < sizeof(OLED_Buffer); i++) {
        OLED_Buffer[i] = 0x00;
    }
}

/**
 * @brief Fill display with color
 */
void OLED_Fill(uint8_t color)
{
    uint8_t fill = color ? 0xFF : 0x00;
    for (uint16_t i = 0; i < sizeof(OLED_Buffer); i++) {
        OLED_Buffer[i] = fill;
    }
}

/**
 * @brief Update display from buffer
 */
void OLED_Display(void)
{
${config.oled.driver === 'SH1106' ? `    for (uint8_t page = 0; page < OLED_PAGES; page++) {
        OLED_WriteCmd(0xB0 + page);
        OLED_WriteCmd(0x02);  // SH1106 column offset
        OLED_WriteCmd(0x10);
        for (uint8_t col = 0; col < OLED_WIDTH; col++) {
            OLED_WriteData(OLED_Buffer[page * OLED_WIDTH + col]);
        }
    }` : `    OLED_WriteCmd(0x21);  // Set column address
    OLED_WriteCmd(0);     // Start column
    OLED_WriteCmd(OLED_WIDTH - 1);  // End column

    OLED_WriteCmd(0x22);  // Set page address
    OLED_WriteCmd(0);     // Start page
    OLED_WriteCmd(OLED_PAGES - 1);  // End page

${isHAL && isI2C ? `    for (uint16_t i = 0; i < sizeof(OLED_Buffer); i++) {
        OLED_WriteData(OLED_Buffer[i]);
    }` : `    for (uint16_t i = 0; i < sizeof(OLED_Buffer); i++) {
        OLED_WriteData(OLED_Buffer[i]);
    }`}`}
}

/**
 * @brief Set pixel in buffer
 */
void OLED_SetPixel(uint8_t x, uint8_t y, uint8_t color)
{
    if (x >= OLED_WIDTH || y >= OLED_HEIGHT) return;

    if (color) {
        OLED_Buffer[x + (y / 8) * OLED_WIDTH] |= (1 << (y % 8));
    } else {
        OLED_Buffer[x + (y / 8) * OLED_WIDTH] &= ~(1 << (y % 8));
    }
}

/**
 * @brief Get pixel from buffer
 */
uint8_t OLED_GetPixel(uint8_t x, uint8_t y)
{
    if (x >= OLED_WIDTH || y >= OLED_HEIGHT) return 0;
    return (OLED_Buffer[x + (y / 8) * OLED_WIDTH] >> (y % 8)) & 1;
}

/**
 * @brief Draw line using Bresenham algorithm
 */
void OLED_DrawLine(uint8_t x0, uint8_t y0, uint8_t x1, uint8_t y1, uint8_t color)
{
    int16_t dx = abs((int16_t)x1 - x0);
    int16_t dy = abs((int16_t)y1 - y0);
    int16_t sx = x0 < x1 ? 1 : -1;
    int16_t sy = y0 < y1 ? 1 : -1;
    int16_t err = dx - dy;

    while (1) {
        OLED_SetPixel(x0, y0, color);
        if (x0 == x1 && y0 == y1) break;
        int16_t e2 = 2 * err;
        if (e2 > -dy) { err -= dy; x0 += sx; }
        if (e2 < dx) { err += dx; y0 += sy; }
    }
}

/**
 * @brief Draw rectangle outline
 */
void OLED_DrawRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color)
{
    OLED_DrawLine(x, y, x + w - 1, y, color);
    OLED_DrawLine(x + w - 1, y, x + w - 1, y + h - 1, color);
    OLED_DrawLine(x + w - 1, y + h - 1, x, y + h - 1, color);
    OLED_DrawLine(x, y + h - 1, x, y, color);
}

/**
 * @brief Draw filled rectangle
 */
void OLED_FillRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t color)
{
    for (uint8_t i = 0; i < h; i++) {
        for (uint8_t j = 0; j < w; j++) {
            OLED_SetPixel(x + j, y + i, color);
        }
    }
}

/**
 * @brief Draw circle outline
 */
void OLED_DrawCircle(uint8_t x0, uint8_t y0, uint8_t r, uint8_t color)
{
    int16_t x = r;
    int16_t y = 0;
    int16_t err = 0;

    while (x >= y) {
        OLED_SetPixel(x0 + x, y0 + y, color);
        OLED_SetPixel(x0 + y, y0 + x, color);
        OLED_SetPixel(x0 - y, y0 + x, color);
        OLED_SetPixel(x0 - x, y0 + y, color);
        OLED_SetPixel(x0 - x, y0 - y, color);
        OLED_SetPixel(x0 - y, y0 - x, color);
        OLED_SetPixel(x0 + y, y0 - x, color);
        OLED_SetPixel(x0 + x, y0 - y, color);

        y++;
        if (err <= 0) {
            err += 2 * y + 1;
        }
        if (err > 0) {
            x--;
            err -= 2 * x + 1;
        }
    }
}

/**
 * @brief Draw filled circle
 */
void OLED_FillCircle(uint8_t x0, uint8_t y0, uint8_t r, uint8_t color)
{
    for (int16_t y = -r; y <= r; y++) {
        for (int16_t x = -r; x <= r; x++) {
            if (x * x + y * y <= r * r) {
                OLED_SetPixel(x0 + x, y0 + y, color);
            }
        }
    }
}

/**
 * @brief Draw rounded rectangle outline
 */
void OLED_DrawRoundRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t r, uint8_t color)
{
    // Draw straight edges
    OLED_DrawLine(x + r, y, x + w - r - 1, y, color);
    OLED_DrawLine(x + r, y + h - 1, x + w - r - 1, y + h - 1, color);
    OLED_DrawLine(x, y + r, x, y + h - r - 1, color);
    OLED_DrawLine(x + w - 1, y + r, x + w - 1, y + h - r - 1, color);

    // Draw corners
    int16_t cx = r;
    int16_t cy = 0;
    int16_t err = 0;

    while (cx >= cy) {
        OLED_SetPixel(x + w - r - 1 + cx, y + r - cy, color);
        OLED_SetPixel(x + w - r - 1 + cy, y + r - cx, color);
        OLED_SetPixel(x + r - cy, y + r - cx, color);
        OLED_SetPixel(x + r - cx, y + r - cy, color);
        OLED_SetPixel(x + r - cx, y + h - r - 1 + cy, color);
        OLED_SetPixel(x + r - cy, y + h - r - 1 + cx, color);
        OLED_SetPixel(x + w - r - 1 + cy, y + h - r - 1 + cx, color);
        OLED_SetPixel(x + w - r - 1 + cx, y + h - r - 1 + cy, color);

        cy++;
        if (err <= 0) err += 2 * cy + 1;
        if (err > 0) { cx--; err -= 2 * cx + 1; }
    }
}

/**
 * @brief Draw filled rounded rectangle
 */
void OLED_FillRoundRect(uint8_t x, uint8_t y, uint8_t w, uint8_t h, uint8_t r, uint8_t color)
{
    OLED_FillRect(x + r, y, w - 2 * r, h, color);
    OLED_FillRect(x, y + r, r, h - 2 * r, color);
    OLED_FillRect(x + w - r, y + r, r, h - 2 * r, color);

    OLED_FillCircle(x + r, y + r, r, color);
    OLED_FillCircle(x + w - r - 1, y + r, r, color);
    OLED_FillCircle(x + r, y + h - r - 1, r, color);
    OLED_FillCircle(x + w - r - 1, y + h - r - 1, r, color);
}

/**
 * @brief Draw character
 */
void OLED_DrawChar(uint8_t x, uint8_t y, char c, uint8_t size, uint8_t color)
{
    if (c < 32 || c > 126) c = '?';
    const uint8_t* charData = Font_6x8[c - 32];

    uint8_t scale = size / 8;
    if (scale < 1) scale = 1;

    for (uint8_t col = 0; col < 6; col++) {
        uint8_t line = charData[col];
        for (uint8_t row = 0; row < 8; row++) {
            if (line & (1 << row)) {
                for (uint8_t sy = 0; sy < scale; sy++) {
                    for (uint8_t sx = 0; sx < scale; sx++) {
                        OLED_SetPixel(x + col * scale + sx, y + row * scale + sy, color);
                    }
                }
            }
        }
    }
}

/**
 * @brief Draw string
 */
void OLED_DrawString(uint8_t x, uint8_t y, const char* str, uint8_t size, uint8_t color)
{
    uint8_t scale = size / 8;
    if (scale < 1) scale = 1;

    while (*str) {
        OLED_DrawChar(x, y, *str, size, color);
        x += 6 * scale;
        str++;
    }
}

/**
 * @brief Draw bitmap
 */
void OLED_DrawBitmap(uint8_t x, uint8_t y, uint8_t w, uint8_t h, const uint8_t* bitmap, uint8_t color)
{
    uint8_t pages = (h + 7) / 8;

    for (uint8_t page = 0; page < pages; page++) {
        for (uint8_t col = 0; col < w; col++) {
            uint8_t data = bitmap[page * w + col];
            for (uint8_t bit = 0; bit < 8; bit++) {
                uint8_t py = page * 8 + bit;
                if (py >= h) break;
                if (data & (1 << bit)) {
                    OLED_SetPixel(x + col, y + py, color);
                }
            }
        }
    }
}
`
}

function getInitSequence(driver: string): string {
  const cmds: string[] = []

  if (driver === 'SH1106') {
    cmds.push(
      'OLED_WriteCmd(0xAE);  // Display OFF',
      'OLED_WriteCmd(0x02);  // Set lower column address',
      'OLED_WriteCmd(0x10);  // Set higher column address',
      'OLED_WriteCmd(0x40);  // Set display start line',
      'OLED_WriteCmd(0xB0);  // Set page address',
      'OLED_WriteCmd(0x81);  // Set contrast',
      'OLED_WriteCmd(0xCF);',
      'OLED_WriteCmd(0xA1);  // Set segment remap',
      'OLED_WriteCmd(0xA6);  // Normal display',
      'OLED_WriteCmd(0xA8);  // Set multiplex ratio',
      'OLED_WriteCmd(0x3F);',
      'OLED_WriteCmd(0xC8);  // COM scan direction',
      'OLED_WriteCmd(0xD3);  // Set display offset',
      'OLED_WriteCmd(0x00);',
      'OLED_WriteCmd(0xD5);  // Set clock divide',
      'OLED_WriteCmd(0x80);',
      'OLED_WriteCmd(0xD9);  // Set pre-charge period',
      'OLED_WriteCmd(0xF1);',
      'OLED_WriteCmd(0xDA);  // Set COM pins',
      'OLED_WriteCmd(0x12);',
      'OLED_WriteCmd(0xDB);  // Set VCOMH',
      'OLED_WriteCmd(0x40);',
      'OLED_WriteCmd(0x8D);  // Enable charge pump',
      'OLED_WriteCmd(0x14);',
      'OLED_WriteCmd(0xAF);  // Display ON'
    )
  } else {
    // SSD1306 / SSD1309
    cmds.push(
      'OLED_WriteCmd(0xAE);  // Display OFF',
      'OLED_WriteCmd(0xD5);  // Set clock divide ratio',
      'OLED_WriteCmd(0x80);',
      'OLED_WriteCmd(0xA8);  // Set multiplex ratio',
      'OLED_WriteCmd(OLED_HEIGHT - 1);',
      'OLED_WriteCmd(0xD3);  // Set display offset',
      'OLED_WriteCmd(0x00);',
      'OLED_WriteCmd(0x40);  // Set display start line',
      'OLED_WriteCmd(0x8D);  // Enable charge pump',
      'OLED_WriteCmd(0x14);',
      'OLED_WriteCmd(0x20);  // Set memory mode',
      'OLED_WriteCmd(0x00);  // Horizontal addressing',
      'OLED_WriteCmd(0xA1);  // Set segment remap',
      'OLED_WriteCmd(0xC8);  // COM scan direction',
      'OLED_WriteCmd(0xDA);  // Set COM pins',
      'OLED_WriteCmd(OLED_HEIGHT == 64 ? 0x12 : 0x02);',
      'OLED_WriteCmd(0x81);  // Set contrast',
      'OLED_WriteCmd(0xCF);',
      'OLED_WriteCmd(0xD9);  // Set pre-charge period',
      'OLED_WriteCmd(0xF1);',
      'OLED_WriteCmd(0xDB);  // Set VCOMH',
      'OLED_WriteCmd(0x40);',
      'OLED_WriteCmd(0xA4);  // Display from RAM',
      'OLED_WriteCmd(0xA6);  // Normal display',
      'OLED_WriteCmd(0xAF);  // Display ON'
    )
  }

  return '    ' + cmds.join('\n    ')
}

function generateFontHeader(): string {
  return `/**
 * @file    oled_font.h
 * @brief   OLED Font Data (6x8)
 * @note    Generated by OLED GUI Editor
 */

#ifndef __OLED_FONT_H
#define __OLED_FONT_H

#include <stdint.h>

/* 6x8 ASCII Font (characters 32-126) */
static const uint8_t Font_6x8[][6] = {
    {0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, // Space
    {0x00, 0x00, 0x5F, 0x00, 0x00, 0x00}, // !
    {0x00, 0x07, 0x00, 0x07, 0x00, 0x00}, // "
    {0x14, 0x7F, 0x14, 0x7F, 0x14, 0x00}, // #
    {0x24, 0x2A, 0x7F, 0x2A, 0x12, 0x00}, // $
    {0x23, 0x13, 0x08, 0x64, 0x62, 0x00}, // %
    {0x36, 0x49, 0x55, 0x22, 0x50, 0x00}, // &
    {0x00, 0x05, 0x03, 0x00, 0x00, 0x00}, // '
    {0x00, 0x1C, 0x22, 0x41, 0x00, 0x00}, // (
    {0x00, 0x41, 0x22, 0x1C, 0x00, 0x00}, // )
    {0x08, 0x2A, 0x1C, 0x2A, 0x08, 0x00}, // *
    {0x08, 0x08, 0x3E, 0x08, 0x08, 0x00}, // +
    {0x00, 0x50, 0x30, 0x00, 0x00, 0x00}, // ,
    {0x08, 0x08, 0x08, 0x08, 0x08, 0x00}, // -
    {0x00, 0x60, 0x60, 0x00, 0x00, 0x00}, // .
    {0x20, 0x10, 0x08, 0x04, 0x02, 0x00}, // /
    {0x3E, 0x51, 0x49, 0x45, 0x3E, 0x00}, // 0
    {0x00, 0x42, 0x7F, 0x40, 0x00, 0x00}, // 1
    {0x42, 0x61, 0x51, 0x49, 0x46, 0x00}, // 2
    {0x21, 0x41, 0x45, 0x4B, 0x31, 0x00}, // 3
    {0x18, 0x14, 0x12, 0x7F, 0x10, 0x00}, // 4
    {0x27, 0x45, 0x45, 0x45, 0x39, 0x00}, // 5
    {0x3C, 0x4A, 0x49, 0x49, 0x30, 0x00}, // 6
    {0x01, 0x71, 0x09, 0x05, 0x03, 0x00}, // 7
    {0x36, 0x49, 0x49, 0x49, 0x36, 0x00}, // 8
    {0x06, 0x49, 0x49, 0x29, 0x1E, 0x00}, // 9
    {0x00, 0x36, 0x36, 0x00, 0x00, 0x00}, // :
    {0x00, 0x56, 0x36, 0x00, 0x00, 0x00}, // ;
    {0x00, 0x08, 0x14, 0x22, 0x41, 0x00}, // <
    {0x14, 0x14, 0x14, 0x14, 0x14, 0x00}, // =
    {0x41, 0x22, 0x14, 0x08, 0x00, 0x00}, // >
    {0x02, 0x01, 0x51, 0x09, 0x06, 0x00}, // ?
    {0x32, 0x49, 0x79, 0x41, 0x3E, 0x00}, // @
    {0x7E, 0x11, 0x11, 0x11, 0x7E, 0x00}, // A
    {0x7F, 0x49, 0x49, 0x49, 0x36, 0x00}, // B
    {0x3E, 0x41, 0x41, 0x41, 0x22, 0x00}, // C
    {0x7F, 0x41, 0x41, 0x22, 0x1C, 0x00}, // D
    {0x7F, 0x49, 0x49, 0x49, 0x41, 0x00}, // E
    {0x7F, 0x09, 0x09, 0x01, 0x01, 0x00}, // F
    {0x3E, 0x41, 0x41, 0x51, 0x32, 0x00}, // G
    {0x7F, 0x08, 0x08, 0x08, 0x7F, 0x00}, // H
    {0x00, 0x41, 0x7F, 0x41, 0x00, 0x00}, // I
    {0x20, 0x40, 0x41, 0x3F, 0x01, 0x00}, // J
    {0x7F, 0x08, 0x14, 0x22, 0x41, 0x00}, // K
    {0x7F, 0x40, 0x40, 0x40, 0x40, 0x00}, // L
    {0x7F, 0x02, 0x04, 0x02, 0x7F, 0x00}, // M
    {0x7F, 0x04, 0x08, 0x10, 0x7F, 0x00}, // N
    {0x3E, 0x41, 0x41, 0x41, 0x3E, 0x00}, // O
    {0x7F, 0x09, 0x09, 0x09, 0x06, 0x00}, // P
    {0x3E, 0x41, 0x51, 0x21, 0x5E, 0x00}, // Q
    {0x7F, 0x09, 0x19, 0x29, 0x46, 0x00}, // R
    {0x46, 0x49, 0x49, 0x49, 0x31, 0x00}, // S
    {0x01, 0x01, 0x7F, 0x01, 0x01, 0x00}, // T
    {0x3F, 0x40, 0x40, 0x40, 0x3F, 0x00}, // U
    {0x1F, 0x20, 0x40, 0x20, 0x1F, 0x00}, // V
    {0x7F, 0x20, 0x18, 0x20, 0x7F, 0x00}, // W
    {0x63, 0x14, 0x08, 0x14, 0x63, 0x00}, // X
    {0x03, 0x04, 0x78, 0x04, 0x03, 0x00}, // Y
    {0x61, 0x51, 0x49, 0x45, 0x43, 0x00}, // Z
    {0x00, 0x00, 0x7F, 0x41, 0x41, 0x00}, // [
    {0x02, 0x04, 0x08, 0x10, 0x20, 0x00}, // backslash
    {0x41, 0x41, 0x7F, 0x00, 0x00, 0x00}, // ]
    {0x04, 0x02, 0x01, 0x02, 0x04, 0x00}, // ^
    {0x40, 0x40, 0x40, 0x40, 0x40, 0x00}, // _
    {0x00, 0x01, 0x02, 0x04, 0x00, 0x00}, // \`
    {0x20, 0x54, 0x54, 0x54, 0x78, 0x00}, // a
    {0x7F, 0x48, 0x44, 0x44, 0x38, 0x00}, // b
    {0x38, 0x44, 0x44, 0x44, 0x20, 0x00}, // c
    {0x38, 0x44, 0x44, 0x48, 0x7F, 0x00}, // d
    {0x38, 0x54, 0x54, 0x54, 0x18, 0x00}, // e
    {0x08, 0x7E, 0x09, 0x01, 0x02, 0x00}, // f
    {0x08, 0x14, 0x54, 0x54, 0x3C, 0x00}, // g
    {0x7F, 0x08, 0x04, 0x04, 0x78, 0x00}, // h
    {0x00, 0x44, 0x7D, 0x40, 0x00, 0x00}, // i
    {0x20, 0x40, 0x44, 0x3D, 0x00, 0x00}, // j
    {0x00, 0x7F, 0x10, 0x28, 0x44, 0x00}, // k
    {0x00, 0x41, 0x7F, 0x40, 0x00, 0x00}, // l
    {0x7C, 0x04, 0x18, 0x04, 0x78, 0x00}, // m
    {0x7C, 0x08, 0x04, 0x04, 0x78, 0x00}, // n
    {0x38, 0x44, 0x44, 0x44, 0x38, 0x00}, // o
    {0x7C, 0x14, 0x14, 0x14, 0x08, 0x00}, // p
    {0x08, 0x14, 0x14, 0x18, 0x7C, 0x00}, // q
    {0x7C, 0x08, 0x04, 0x04, 0x08, 0x00}, // r
    {0x48, 0x54, 0x54, 0x54, 0x20, 0x00}, // s
    {0x04, 0x3F, 0x44, 0x40, 0x20, 0x00}, // t
    {0x3C, 0x40, 0x40, 0x20, 0x7C, 0x00}, // u
    {0x1C, 0x20, 0x40, 0x20, 0x1C, 0x00}, // v
    {0x3C, 0x40, 0x30, 0x40, 0x3C, 0x00}, // w
    {0x44, 0x28, 0x10, 0x28, 0x44, 0x00}, // x
    {0x0C, 0x50, 0x50, 0x50, 0x3C, 0x00}, // y
    {0x44, 0x64, 0x54, 0x4C, 0x44, 0x00}, // z
    {0x00, 0x08, 0x36, 0x41, 0x00, 0x00}, // {
    {0x00, 0x00, 0x7F, 0x00, 0x00, 0x00}, // |
    {0x00, 0x41, 0x36, 0x08, 0x00, 0x00}, // }
    {0x08, 0x08, 0x2A, 0x1C, 0x08, 0x00}, // ~
};

#endif /* __OLED_FONT_H */
`
}

function generateGUIHeader(project: Project): string {
  const pageEnums = project.pages.map((p, i) =>
    `    PAGE_${sanitizeName(p.name).toUpperCase()} = ${i}`
  ).join(',\n')

  return `/**
 * @file    oled_gui.h
 * @brief   OLED GUI Framework
 * @note    Generated by OLED GUI Editor
 */

#ifndef __OLED_GUI_H
#define __OLED_GUI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include "oled_driver.h"

/* Page IDs */
typedef enum {
${pageEnums},
    PAGE_COUNT
} PageID;

/* Page transition effects (handled internally) */
typedef enum {
    GUI_TRANSITION_NONE = 0,
    GUI_TRANSITION_SLIDE_LEFT,
    GUI_TRANSITION_SLIDE_RIGHT,
    GUI_TRANSITION_FADE
} GUI_Transition;

/* GUI events (triggered by hardware/input layer) */
typedef enum {
    GUI_EVENT_NONE = 0,
    GUI_EVENT_KEY_UP,
    GUI_EVENT_KEY_DOWN,
    GUI_EVENT_KEY_LEFT,
    GUI_EVENT_KEY_RIGHT,
    GUI_EVENT_KEY_OK,
    GUI_EVENT_KEY_BACK,
    GUI_EVENT_TIMER,
    GUI_EVENT_CONDITION
} GUI_EventID;

/* Page link descriptor */
typedef struct {
    GUI_EventID trigger;
    PageID target;
    GUI_Transition transition;
} GUI_PageLink;

/* Page Structure */
typedef struct {
    void (*init)(void);
    void (*render)(void);
    void (*onEvent)(GUI_EventID eventId);
    const GUI_PageLink* links;
    uint8_t linkCount;
} GUI_PageDef;

/* GUI Functions */
void GUI_Init(void);
PageID GUI_GetCurrentPage(void);
void GUI_Refresh(void);
void GUI_GoToPage(PageID id);
void GUI_TriggerEvent(GUI_EventID eventId);
void GUI_Update(void);

#ifdef __cplusplus
}
#endif

#endif /* __OLED_GUI_H */
`
}

function generateGUISource(project: Project): string {
  const pageIncludes = project.pages.map(p =>
    `#include "page_${sanitizeName(p.name)}.h"`
  ).join('\n')

  const linkArrays = project.pages.map(p => generatePageLinkArray(p, project.pages)).join('\n\n')

  const pageArrayInit = project.pages.map(p => {
    const name = sanitizeName(p.name)
    return `    { Page_${name}_Init, Page_${name}_Render, Page_${name}_OnEvent, Page_${name}_Links, Page_${name}_LinkCount }`
  }).join(',\n')

  return `/**
 * @file    oled_gui.c
 * @brief   OLED GUI Framework Implementation
 * @note    Generated by OLED GUI Editor
 */

#include "oled_gui.h"
${pageIncludes}

${linkArrays}

/* Page Table */
static const GUI_PageDef Pages[PAGE_COUNT] = {
${pageArrayInit}
};

/* Current Page */
static PageID currentPage = 0;
static void GUI_SwitchPage(PageID id, GUI_Transition transition);
static void GUI_PlayTransition(GUI_Transition transition);

/**
 * @brief Initialize GUI
 */
void GUI_Init(void)
{
    OLED_Init();                 /* Display driver init */
    GUI_SwitchPage(0, GUI_TRANSITION_NONE);
}

/**
 * @brief Get current page ID
 */
PageID GUI_GetCurrentPage(void)
{
    return currentPage;
}

/**
 * @brief Refresh display
 */
void GUI_Refresh(void)
{
    OLED_Clear();
    if (Pages[currentPage].render) {
        Pages[currentPage].render();
    }
    OLED_Display();
}

/**
 * @brief Execute transition animation (kept internal to GUI)
 */
static void GUI_PlayTransition(GUI_Transition transition)
{
    switch (transition) {
        case GUI_TRANSITION_SLIDE_LEFT:
            /* TODO: implement slide-left animation */
            break;
        case GUI_TRANSITION_SLIDE_RIGHT:
            /* TODO: implement slide-right animation */
            break;
        case GUI_TRANSITION_FADE:
            /* TODO: implement fade animation */
            break;
        case GUI_TRANSITION_NONE:
        default:
            break;
    }
}

/**
 * @brief Switch to a target page and render it
 */
static void GUI_SwitchPage(PageID id, GUI_Transition transition)
{
    if (id >= PAGE_COUNT) return;

    currentPage = id;
    if (Pages[currentPage].init) {
        Pages[currentPage].init();
    }

    GUI_PlayTransition(transition);
    GUI_Refresh();
}

/**
 * @brief Public API: jump to page (transition handled internally)
 */
void GUI_GoToPage(PageID id)
{
    GUI_SwitchPage(id, GUI_TRANSITION_NONE);
}

/**
 * @brief Public API: trigger GUI event from hardware/input layer
 */
void GUI_TriggerEvent(GUI_EventID eventId)
{
    if (eventId == GUI_EVENT_NONE) return;

    const GUI_PageDef* page = &Pages[currentPage];

    if (page->onEvent) {
        page->onEvent(eventId);
    }

    if (page->links && page->linkCount > 0) {
        for (uint8_t i = 0; i < page->linkCount; i++) {
            const GUI_PageLink* link = &page->links[i];
            if (link->trigger == eventId && link->target < PAGE_COUNT) {
                GUI_SwitchPage(link->target, link->transition);
                return;
            }
        }
    }

    GUI_Refresh();
}

/**
 * @brief Main GUI update (call in main loop)
 */
void GUI_Update(void)
{
    GUI_Refresh();
}
`
}

function generatePageHeader(page: Page, _config: ProjectConfig): string {
  const name = sanitizeName(page.name)
  const nameCaps = name.toUpperCase()

  return `/**
 * @file    page_${name}.h
 * @brief   Page: ${page.name}
 * @note    Generated by OLED GUI Editor
 */

#ifndef __PAGE_${nameCaps}_H
#define __PAGE_${nameCaps}_H

#ifdef __cplusplus
extern "C" {
#endif

#include "oled_gui.h"

void Page_${name}_Init(void);
void Page_${name}_Render(void);
void Page_${name}_OnEvent(GUI_EventID eventId);

#ifdef __cplusplus
}
#endif

#endif /* __PAGE_${nameCaps}_H */
`
}

function generatePageSource(page: Page, config: ProjectConfig): string {
  const name = sanitizeName(page.name)
  const renderCode = generatePageRenderCode(page, config)

  return `/**
 * @file    page_${name}.c
 * @brief   Page: ${page.name}
 * @note    Generated by OLED GUI Editor
 */

#include "page_${name}.h"

/**
 * @brief Initialize page
 */
void Page_${name}_Init(void)
{
    // Page initialization code
}

/**
 * @brief Render page content
 */
void Page_${name}_Render(void)
{
${renderCode}
}

/**
 * @brief Handle GUI events (state only, navigation handled by GUI core)
 */
void Page_${name}_OnEvent(GUI_EventID eventId)
{
    (void)eventId;
    // Event handling code
}
`
}

function generatePageRenderCode(page: Page, _config: ProjectConfig): string {
  const lines: string[] = []

  // Background
  if (page.backgroundColor === 1) {
    lines.push('    OLED_Fill(OLED_COLOR_WHITE);')
  }

  // Sort elements by zIndex
  const sortedElements = [...page.elements].sort((a, b) => a.zIndex - b.zIndex)

  for (const element of sortedElements) {
    if (!element.visible) continue

    const color = element.properties.color === 1 ? 'OLED_COLOR_WHITE' : 'OLED_COLOR_BLACK'

    switch (element.type) {
      case 'pixel':
        lines.push(`    OLED_SetPixel(${element.x}, ${element.y}, ${color});`)
        break

      case 'line':
        const x2 = element.x + (element.properties.x2 || 0)
        const y2 = element.y + (element.properties.y2 || 0)
        lines.push(`    OLED_DrawLine(${element.x}, ${element.y}, ${x2}, ${y2}, ${color});`)
        break

      case 'rect':
        // Canvas boundaries include endpoints; export width/height +1 to stay aligned
        const rectW = element.width + 1
        const rectH = element.height + 1
        if (element.properties.fill) {
          lines.push(`    OLED_FillRect(${element.x}, ${element.y}, ${rectW}, ${rectH}, ${color});`)
        } else {
          lines.push(`    OLED_DrawRect(${element.x}, ${element.y}, ${rectW}, ${rectH}, ${color});`)
        }
        break

      case 'circle': {
        const r = Math.floor(element.width / 2)
        const cx = element.x + r
        const cy = element.y + r
        if (element.properties.fill) {
          lines.push(`    OLED_FillCircle(${cx}, ${cy}, ${r}, ${color});`)
        } else {
          lines.push(`    OLED_DrawCircle(${cx}, ${cy}, ${r}, ${color});`)
        }
        break
      }

      case 'roundRect': {
        const rrW = element.width + 1
        const rrH = element.height + 1
        const radius = Math.min(
          element.properties.radius || 4,
          Math.floor(rrW / 2),
          Math.floor(rrH / 2)
        )
        if (element.properties.fill) {
          lines.push(`    OLED_FillRoundRect(${element.x}, ${element.y}, ${rrW}, ${rrH}, ${radius}, ${color});`)
        } else {
          lines.push(`    OLED_DrawRoundRect(${element.x}, ${element.y}, ${rrW}, ${rrH}, ${radius}, ${color});`)
        }
        break
      }

      case 'text':
        if (element.properties.text) {
          const size = element.properties.fontSize || 8
          lines.push(`    OLED_DrawString(${element.x}, ${element.y}, "${element.properties.text}", ${size}, ${color});`)
        }
        break

      case 'image':
        // Image data would need to be exported separately
        lines.push(`    // TODO: Draw image at (${element.x}, ${element.y})`)
        break
    }
  }

  return lines.length > 0 ? lines.join('\n') : '    // Empty page'
}

function generatePageLinkArray(page: Page, pages: Page[]): string {
  const arrayName = `Page_${sanitizeName(page.name)}_Links`

  if (page.links.length === 0) {
    return `static const GUI_PageLink* ${arrayName} = NULL;\nstatic const uint8_t ${arrayName}_LinkCount = 0;`
  }

  const entries = page.links.map(link => {
    const trigger = mapTriggerToEventId(link.trigger)
    const target = findTargetPageEnum(link.targetPageId, pages)
    const transition = mapTransitionToEnum(link.transition)
    return `    { ${trigger}, ${target}, ${transition} }`
  }).join(',\n')

  return `static const GUI_PageLink ${arrayName}[] = {\n${entries}\n};\nstatic const uint8_t ${arrayName}_LinkCount = sizeof(${arrayName}) / sizeof(GUI_PageLink);`
}

function mapTriggerToEventId(trigger: PageLink['trigger']): string {
  switch (trigger) {
    case 'KEY_UP':
      return 'GUI_EVENT_KEY_UP'
    case 'KEY_DOWN':
      return 'GUI_EVENT_KEY_DOWN'
    case 'KEY_LEFT':
      return 'GUI_EVENT_KEY_LEFT'
    case 'KEY_RIGHT':
      return 'GUI_EVENT_KEY_RIGHT'
    case 'KEY_OK':
      return 'GUI_EVENT_KEY_OK'
    case 'KEY_BACK':
      return 'GUI_EVENT_KEY_BACK'
    case 'TIMER':
      return 'GUI_EVENT_TIMER'
    case 'CONDITION':
      return 'GUI_EVENT_CONDITION'
    default:
      return 'GUI_EVENT_NONE'
  }
}

function mapTransitionToEnum(transition: PageLink['transition']): string {
  switch (transition) {
    case 'SLIDE_LEFT':
      return 'GUI_TRANSITION_SLIDE_LEFT'
    case 'SLIDE_RIGHT':
      return 'GUI_TRANSITION_SLIDE_RIGHT'
    case 'FADE':
      return 'GUI_TRANSITION_FADE'
    case 'NONE':
    default:
      return 'GUI_TRANSITION_NONE'
  }
}

function findTargetPageEnum(targetPageId: string, pages: Page[]): string {
  const target = pages.find(p => p.id === targetPageId)
  if (!target) return 'PAGE_COUNT'
  return `PAGE_${sanitizeName(target.name).toUpperCase()}`
}

function generateImagesHeader(elements: Element[], config: ProjectConfig): string {
  const date = new Date().toISOString().split('T')[0]
  const imageDeclarations: string[] = []
  const imageData: string[] = []

  for (let i = 0; i < elements.length; i++) {
    const el = elements[i]
    if (!el.properties.imageData) continue

    const imgName = `img_${sanitizeName(el.id.slice(0, 8))}_${i}`
    const width = el.width
    const height = el.height
    const pages = Math.ceil(height / 8)

    // Generate placeholder byte array (actual conversion would happen at export time)
    // For now, generate a pattern based on element properties
    const byteCount = width * pages
    const bytes: number[] = []

    // If we have actual processed data, use it; otherwise generate placeholder
    if (el.properties.processedData) {
      // Use pre-processed data
      const data = el.properties.processedData as number[]
      bytes.push(...data)
    } else {
      // Generate placeholder pattern
      for (let j = 0; j < byteCount; j++) {
        bytes.push(0x00)
      }
    }

    // Format bytes as C array
    const bytesPerRow = 16
    const byteLines: string[] = []
    for (let j = 0; j < bytes.length; j += bytesPerRow) {
      const rowBytes = bytes.slice(j, Math.min(j + bytesPerRow, bytes.length))
      const hexStr = rowBytes.map(b => `0x${b.toString(16).padStart(2, '0').toUpperCase()}`).join(', ')
      const isLast = j + bytesPerRow >= bytes.length
      byteLines.push(`    ${hexStr}${isLast ? '' : ','}`)
    }

    imageData.push(`/* Image: ${imgName} (${width}x${height}) */
static const uint8_t ${imgName}[] = {
${byteLines.join('\n')}
};
static const uint16_t ${imgName}_width = ${width};
static const uint16_t ${imgName}_height = ${height};
`)

    imageDeclarations.push(`extern const uint8_t ${imgName}[];`)
    imageDeclarations.push(`extern const uint16_t ${imgName}_width;`)
    imageDeclarations.push(`extern const uint16_t ${imgName}_height;`)
  }

  return `/**
 * @file    oled_images.h
 * @brief   OLED Image Data
 * @author  ${config.author || 'OLED GUI Editor'}
 * @date    ${date}
 * @note    Generated by OLED GUI Editor
 *
 * Image format: ${config.codeGen.arrayFormat === 'COLUMN' ? 'Column-major (page mode)' : 'Row-major'}
 * Bit order: ${config.codeGen.bitOrder}
 */

#ifndef __OLED_IMAGES_H
#define __OLED_IMAGES_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Image count: ${elements.length} */

${imageData.join('\n')}

#ifdef __cplusplus
}
#endif

#endif /* __OLED_IMAGES_H */
`
}
